### ISSUE TITLE
Cursor visible in non-focused inputs (any UI theme)

### ISSUE THREAD

**Issue by reallyely** [trevordmiller/nova-atom-syntax#15] opened 2016-09-23 17:23 UTC
![image](https://cloud.githubusercontent.com/assets/1640588/18794994/46e3f0cc-8190-11e6-9561-8e6ee915b9e3.png)

Windows 7, 
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by trevordmiller** [comment] 2016-09-23 17:24
@sely1986 I just reproduced this, thanks for letting me know. I'll fix it. Also, it looks like you are overriding cursor color with the orange? Here is default:
![image](https://cloud.githubusercontent.com/assets/5497885/18795138/54aa4216-8180-11e6-9729-55da508d7a36.png)

**Comment by sely1986** [comment] 2016-09-23 20:38
Yeah, I've got some styles.less funkiness cluttering up the works here and there.  Thanks for the great theme!

**Comment by trevordmiller** [comment] 2016-11-14 04:10
I'm closing this for now, since it is lower priority than other things I'm working on. If anyone would like to re-open the issue and submit a pull request, let me know! I'd be happy to have your contribution :)

**Closed by trevordmiller** 2016-11-14 04:10 UTC
Labels: bug, help wanted
